version: '3.8'

services:
  app:
    image: vipcb04/flight-schedules:latest
    container_name: flight-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d5n37bdactks73c7lj5g-a.singapore-postgres.render.com:5432/airlab
      SPRING_DATASOURCE_USERNAME: airlab_user
      SPRING_DATASOURCE_PASSWORD: ifhIjDDTmlUhT5owTW4oMc1mQhJjeTB9
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    restart: unless-stopped