version: '3.8'

services:
  

  app:
    image: vipcb04/airhub:latest
    container_name: flight-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/airlab_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8080:8080"
    networks:
      - flight-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  flight-network:
    driver: bridge
